
before_telein_cols = {
    'query':str,
    'name':str,
    'site':str,
    'type':str,
    'subtypes':str,
    'category':str,
    'phone':str,
    'full_address':str,
    'borough':str,
    'street':str,
    'city':str,
    'postal_code':str,
    'state':str,
    'us_state':str,
    'country':str,
    'country_code':str,
    'latitude':str,
    'longitude':str,
    'time_zone':str,
    'plus_code':str,
    'area_service':str,
    'rating':str,
    'reviews':str,
    'reviews_link':str,
    'reviews_tags':str,
    'reviews_per_score':str,
    'reviews_per_score_1':str,
    'reviews_per_score_2':str,
    'reviews_per_score_3':str,
    'reviews_per_score_4':str,
    'reviews_per_score_5':str,
    'photos_count':str,
    'photo':str,
    'street_view':str,
    'located_in':str,
    'working_hours':str,
    'working_hours_old_format':str,
    'other_hours':str,
    'popular_times':str,
    'business_status':str,
    'about':str,
    'range':str,
    'posts':str,
    'logo':str,
    'description':str,
    'verified':str,
    'owner_id':str,
    'owner_title':str,
    'owner_link':str,
    'reservation_links':str,
    'booking_appointment_link':str,
    'menu_link':str,
    'order_links':str,
    'location_link':str,
    'place_id':str,
    'google_id':str,
    'cid':str,
    'reviews_id':str,
    'located_google_id':str,
}

after_telein_cols = {
    'internalId': str,
    'extractionId': str,
    'place_id': str,
    'google_id': str,
    'cid': str,
    'query_search': str,
    'query_keyword': str,
    'query_neighborhood': str,
    'query_location_city': str,
    'query_location_state': str,
    'query_location_country': str,
    'name': str,
    'site': str,
    'type': str,
    'category': str,
    'phone': str,
    'address_full': str,
    'address_neighborhood': str,
    'address_street': str,
    'address_city': str,
    'address_postal_code': str,
    'address_state': str,
    'address_country': str,
    'address_country_code': str,
    'latitude': float,
    'longitude': float,
    'area_service': bool,
    'rating': float,
    'reviews_quantity': str,
    'reviews_per_score_1': str,
    'reviews_per_score_2': str,
    'reviews_per_score_3': str,
    'reviews_per_score_4': str,
    'reviews_per_score_5': str,
    'business_status': str,
    'range': str,
    'logo': str,
    'description': str,
    'verified': str,
    'owner_id': str,
    'owner_title': str,
    'phone_ddi': str,
    'phone_ddd': str,
    'phone_number': str,
    'phoneOperator_operatorCode': str,
    'phoneOperator_operatorName': str,
    'phoneOperator_operatorMigrated': str,
    'firstSyncAt': str,
    'updateSyncAt': str,
    'internalTag': str
}

states = {
    'São Paulo' : 'SP',
    'Santa Catarina' : 'SC',
    'Rio Grande do Sul' : 'RS',
    'Rio de Janeiro' : 'RJ',
    'Paraná' : 'PR',
    'Minas Gerais' : 'MG',
    'Bahia' : 'BA',
    'Espírito Santo' : 'ES',
    'Distrito Federal': 'DF'
}

cities = [
    'Curitiba',
    'Londrina',
    'Maringá',
    'Ponta Grossa',
    'Cascavel',
    'Florianópolis',
    'Joinville',
    'Blumenau',
    'São José',
    'Criciúma',
    'Porto Alegre',
    'Canoas',
    'Caxias do Sul',
    'Pelotas',
    'Santa Maria',
    'São Paulo',
    'Guarulhos',
    'Campinas',
    'São Bernardo do Campo',
    'Santo André',
    'Rio de Janeiro',
    'São Gonçalo',
    'Duque de Caxias',
    'Nova Iguaçu',
    'Niterói',
    'Belo Horizonte',
    'Uberlândia',
    'Contagem',
    'Juiz de Fora',
    'Betim',
    'Salvador',
    'Feira de Santana',
    'Vitória da Conquista',
    'Camaçari',
    'Itabuna'
]
